services:
  ros2:
    image: yolo_ros
    container_name: ros
    network_mode: host
    privileged: true
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/input/js0:/dev/input/js0"    # map joystick device
      - "/dev/hidraw0:/dev/hidraw0"       # map HID device if needed
    volumes:
      - ~/ros2_dice_ws:/ros2_ws
      - ~/yolo_models:/yolo_models
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    command: tail -f /dev/null
